### ISSUE TITLE
Blurry or cutout. viewBox

### ISSUE THREAD

**Issue by pfaffenrodt** [StanKocken/SVG2Drawable#5]
I think the viewBox offset is not correct handled.

I have blurry or cutout drawables.

**Comment by StanKocken** [comment]
Do you have a SVG example?

**Comment by StanKocken** [comment]
Are you putting this Drawable into an ImageView or as a background of a view or something else? 
If it's an ImageView, are using a "FIT_XY"? Can you try to put it as the background of a View and let me know, just for test.

This drawable has a dimension "minimum". In some case, depending of the ScaleType, Android will use this minimum dimension and scale it.

**Comment by pfaffenrodt** [comment]
setting Drawable ImageView.imageView.setImageDrawable()

I think it happens, if the viewBox is smaller then the View. 

blurry

``` xml
viewBox="0 0 130.4 130.5"
```

sharp

``` xml
viewBox="0 0 1000 1000"
```

**Comment by StanKocken** [comment]
Ok, I know what is the issue.

For the Blurry:
I was using the "getIntrinsicHeight()" and "getIntrinsicWidth()". I should use the "getMinimumHeight()" and "getMinimumWidth()" instead.

For the sharp:
I'm using the viewBox as "the number of pixel minimum for the width" but it's not true. In fact we don't have minimum with the SVG. But we need to keep the ratio width/height. If the viewBox is "0 0 500 1000", so the "getMinimumWidth()" should be "5" (instead of 500 today) and the "getMinimumHeight()" should be "10" (instead of 1000 today).

Again, I will be able to do later today but be free to open a PR if you want.

**Comment by StanKocken** [comment]
I made the fix on a branch, let me know if that works in your case: https://github.com/StanKocken/SVG2Drawable/tree/issue_5

**Comment by pfaffenrodt** [comment]
nice work. Now  all Drawables are clear and sharp.

**Comment by StanKocken** [comment]
Thanks for your help.
